apiVersion: v1
kind: Namespace
metadata:
  name: chaos-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: chaos-app
  labels:
    app: server
  annotations:
    # Annotation for Litmus
    litmuschaos.io/chaos: "true"
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
      annotations:
        # Annotation for Litmus
        litmuschaos.io/chaos: "true"
    spec:
      containers:
        - name: server
          image: iskorotkov/chaos-server:v0.1.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8811
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: chaos-app
spec:
  selector:
    app: server
  ports:
    - port: 8811
      targetPort: 8811
