apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
  annotations:
    # Annotation for Litmus
    litmuschaos.io/chaos: "true"
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
      annotations:
        # Annotation for Litmus
        litmuschaos.io/chaos: "true"
    spec:
      containers:
        - name: server
          image: iskorotkov/chaos-server:v0.1.0
          resources:
            limits:
              memory: "64Mi"
              cpu: "50m"
          ports:
            - name: web
              containerPort: 8811
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - name: web
      port: 8811
      targetPort: 8811
